# Generated by Django 4.2.24 on 2025-09-22 06:10

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitrix24', '0006_auto_20240528_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('custom_priority', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('import', 'Импорт'), ('export', 'Экспорт')], max_length=10)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'В процессе'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('file_name', models.CharField(max_length=255)),
                ('filter_params', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('export_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/export_files'), upload_to='export_files/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitrix24.bitrixuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductQRLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_data', models.JSONField(blank=True, null=True)),
                ('product_images', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitrix24.bitrixuser')),
            ],
        ),
        migrations.CreateModel(
            name='ImportExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_index', models.IntegerField()),
                ('contact_data', models.JSONField()),
                ('bitrix_contact_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='deals.importexportjob')),
            ],
            options={
                'ordering': ['record_index'],
            },
        ),
    ]
