# Generated by Django 4.2.24 on 2025-09-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('type_id', models.CharField(blank=True, max_length=50)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('stage_id', models.CharField(blank=True, max_length=50)),
                ('stage_semantic_id', models.CharField(blank=True, max_length=50)),
                ('is_new', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_return_customer', models.BooleanField(default=False)),
                ('is_repeated_approach', models.BooleanField(default=False)),
                ('probability', models.IntegerField(default=0)),
                ('currency_id', models.CharField(default='RUB', max_length=3)),
                ('opportunity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_manual_opportunity', models.BooleanField(default=False)),
                ('tax_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('contact_id', models.IntegerField(blank=True, null=True)),
                ('quote_id', models.IntegerField(blank=True, null=True)),
                ('lead_id', models.IntegerField(blank=True, null=True)),
                ('begindate', models.DateTimeField(blank=True, null=True)),
                ('closedate', models.DateTimeField(blank=True, null=True)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('date_modify', models.DateTimeField(blank=True, null=True)),
                ('moved_time', models.DateTimeField(blank=True, null=True)),
                ('opened', models.BooleanField(default=True)),
                ('closed', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('source_description', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('assigned_by_id', models.IntegerField(blank=True, null=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('modify_by_id', models.IntegerField(blank=True, null=True)),
                ('moved_by_id', models.IntegerField(blank=True, null=True)),
                ('source_id', models.CharField(blank=True, max_length=50)),
                ('originator_id', models.CharField(blank=True, max_length=255)),
                ('origin_id', models.CharField(blank=True, max_length=255)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('custom_priority', models.CharField(blank=True, max_length=50)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('last_activity_time', models.DateTimeField(blank=True, null=True)),
                ('last_activity_by', models.IntegerField(blank=True, null=True)),
                ('last_communication_time', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
    ]
