# Generated by Django 4.2.24 on 2025-09-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productqrlink',
            name='product_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
