# Generated by Django 4.2.24 on 2025-09-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomDeal',
        ),
    ]
