# Generated by Django 4.2.24 on 2025-09-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0002_delete_customdeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('custom_priority', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
