# Generated by Django 4.2.24 on 2025-09-12 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
