# Generated by Django 4.2.24 on 2025-09-14 07:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0006_auto_20240528_1411'),
        ('deals', '0004_customdeal_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQRLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitrix24.bitrixuser')),
            ],
        ),
    ]
