# Generated by Django 4.2.24 on 2025-09-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_productqrlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='productqrlink',
            name='product_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
